"""profiles table creation

Revision ID: 4e6c665a0e50
Revises: 289549b0e29a
Create Date: 2026-04-15 08:48:08.530400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6c665a0e50'
down_revision: Union[str, Sequence[str], None] = '289549b0e29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('gender_probability', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Enum('CHILD', 'ADULT', 'SENIOR', 'TEENAGER', name='agegroupenum'), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('country_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='profiles_id_pk')
    )
    op.create_index('idx_profiles_age_group', 'profiles', ['age_group'], unique=False)
    op.create_index('idx_profiles_country_id', 'profiles', ['country_id'], unique=False)
    op.create_index('idx_profiles_gender', 'profiles', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profiles_gender', table_name='profiles')
    op.drop_index('idx_profiles_country_id', table_name='profiles')
    op.drop_index('idx_profiles_age_group', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
